---
clickhouse:
  hosts:
    clickhouse:
      ansible_host: 192.168.1.10
      ansible_user: vagrant
      ansible_password: vagrant

vector:
  hosts:
    vector:
      ansible_host: 192.168.1.10
      ansible_user: vagrant
      ansible_password: vagrant