---
vector_version: "0.21.1-1"
vector_os_arh: "x86_64"
vector_workdir: "/home/vagrant/vector"
vector_os_user: "vector"
vector_os_group: "vector"
vector_config:
  sources:
    demo_logs:
      type: demo_logs
      format: syslog
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - demo_logs
      database: logs
      endpoint: http://192.168.1.20:8123
      table: vector_table
      compression: gzip
      healthcheck: true
      skip_unknown_fields: true

