---

- name: test
  gather_facts: false
  hosts: all
  vars:
    ansible_user: ubuntu
  become: yes
  tasks:

  - local_action: wait_for port=22 host="{{ ansible_ssh_host }}"  search_regex=OpenSSH delay=10
  
  - name: Install Nginx Web Server on Debian Family
    apt:
      name: nginx
      state: latest   
      update_cache: yes 