---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: centos
#  gather_facts: false
  roles:
    - role: clickhouse
      tags: clickhouse

- name: Install Vector
  hosts: vector
  gather_facts: false
  remote_user: centos
  roles:
    - role: vector-role
      tags: vector

- name: Lighthouse
  hosts: lighthouse
  gather_facts: false
  remote_user: centos
  roles:
    - role: lighthouse-role
      tags: lighthouse
